{
 "title": "Serving metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total predictions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BENTOML_toxic:comment:classifier_request_total"
    }
   ]
  },
  {
   "title": "Predictions in progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BENTOML_toxic:comment:classifier_request_in_progress"
    }
   ]
  },
  {
   "title": "Prediction latency",
   "type": "bargauge",
   "description": "Request duration for predictions",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BENTOML_toxic:comment:classifier_request_duration_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of predictions per second",
   "type": "timeseries",
   "description": "Total number of predictions per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(BENTOML_toxic:comment:classifier_request_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}